runtime: python312

instance_class: F1

default_expiration: "1d"

handlers:
- url: /static/icons/
  static_dir: static/icons
  expiration: 7d

- url: /static/images
  static_dir: static/images
  expiration: 7d

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/manifest
  static_dir: static/manifest

- url: /.*
  script: main.app
  login: optional
  secure: always

includes:
  - api_keys.yaml
