application: tide-catcher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  expiration: 7d
  upload: favicon\.ico

- url: /image
  static_dir: image
  expiration: 7d

- url: /style
  static_dir: style

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

