application: tide-catcher
version: 5
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"


handlers:
- url: /(.*icon.*)$
  static_files: icons/\1
  expiration: 7d
  upload: icons/.*icon.*

- url: /images
  static_dir: images
  expiration: 7d

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /(manifest.json|browserconfig.xml)
  static_files: static/\1
  upload: static/*

- url: .*
  script: py.main.app
  login: optional
  secure: always
