application: tide-catcher
version: 6
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /(.*icon.*)$
  static_files: icons/\1
  expiration: 7d
  upload: icons/.*icon.*

- url: /images
  static_dir: images
  expiration: 7d

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(manifest.json|browserconfig.xml)
  static_files: static/\1
  upload: static/*

- url: .*
  script: py.main.app
  login: optional
  secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?index\.yaml$

includes:
  - api_keys.yaml
