application: tide-catcher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*icon.*)$
  static_files: icons/\1
  expiration: 7d

- url: /images
  static_dir: images
  expiration: 7d

- url: /styles
  static_dir: styles

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

